### PR TITLE
Add sports release team

### PR DESCRIPTION
**Pull request by ijnek**
Should I fill out the templated issue for this, or a raise a PR like I do here...?

Signed-off-by: Kenji Brameld <kenjibrameld@gmail.com>

* Name of the new release team: sports
* Release repositories to **move from ijnek to sports**:
  * [rcss3d_agent](https://github.com/ros-sports/rcss3d_agent.git)
    * [x] There is an existing release repository which should be imported: <https://github.com/ros2-gbp/rcss3d_agent-release>
  * [ros_image_to_qimage](https://github.com/ros-sports/ros_image_to_qimage)
    * [x] There is an existing release repository which should be imported: <https://github.com/ros2-gbp/ros_image_to_qimage-release>
  * [rqt_image_overlay](https://github.com/ros-sports/rqt_image_overlay)
    * [x] There is an existing release repository which should be imported: <https://github.com/ros2-gbp/rqt_image_overlay-release>

* Team members
  * [@ijnek](https://github.com/ros-sports/rcss3d_agent/blob/0001c5306c370d1504072153aa39492d02a57a21/rcss3d_agent/package.xml#L7)

### CODE REVIEW

**Comment by ijnek** [comment]
Going to wait on #6 getting merged first.

**Comment by nuclearsandwich** [comment]
> Should I fill out the templated issue for this, or a raise a PR like I do here...?

Still ironing out the details in the pre-history of this project all of the issue templates were pull request templates but I'm not sure that GitHub has a template chooser interface for pull requests yet so I could not see a way to advertise multiple PR templates to contributors.

I think in general it would be nice if PRs included the issue template text. I updated this PR with the information I have, if you fill out the rest and rebase this PR we can get this set up. Thanks for being one of the early adopters of the new workflow!

**Comment by ijnek** [comment]
Thanks @nuclearsandwich 
This PR is now about **moving repositories from ijnek_team to sports_team.**
I've rebased and made some modifications to adapt to the new style. Ready for Review.

**Review by nuclearsandwich — APPROVED** [review]
Thanks! I'll merge and deploy this later today.

**Comment by nuclearsandwich** [comment]
This has just been deployed!

**Pull request merged**
