### PR TITLE
Update Apex.AI team with new members

### PR DESCRIPTION
**Pull request by flynneva**
- add future `performance_test-release` repo to team repo list

We are preparing to create a release for [the performance_test suite of packages](https://gitlab.com/ApexAI/performance_test/)

### CODE REVIEW

**Comment by flynneva** [comment]
@nuclearsandwich friendly ping, could you help us out here?  Not sure if we need to ask you to create a new `performance_test-release` repo as well or if that is automated some how...

**Comment by flynneva** [comment]
cc @carlossvg @erikatapex @revati-naik

**Comment by carlossvg** [comment]
@flynneva Could you add @landerU too? He is usually involved in some package maintenance.

**Review by nuclearsandwich — APPROVED** [review]

**Comment by nuclearsandwich** [comment]
This change has been deployed.

**Comment by flynneva** [comment]
@nuclearsandwich thank you for adding @LanderU as well!

**Comment by ErikAtApex** [comment]
@nuclearsandwich thanks for sending an invitation! I was on vacation last week, so the invitation has expired. Would you kindly send another?

**Comment by nuclearsandwich** [comment]
> @nuclearsandwich thanks for sending an invitation! I was on vacation last week, so the invitation has expired. Would you kindly send another?

The most recent deployment included a resent invitation.

**Pull request merged**
