### PR TITLE
Add immel-f to lanelet2_team

### PR DESCRIPTION
**Pull request by immel-f**
I am the new maintainer for lanelet2 and need to be added to lanelet2_team to initiate ROS2 releases.

### CODE REVIEW

**Comment by poggenhans** [comment]
I can confirm 👍 . Please add him.

**Review by nuclearsandwich — APPROVED** [review]
I swapped the names so that lexicographical order is maintained.

**Comment by nuclearsandwich** [comment]
This change has been deployed!

**Comment by poggenhans** [comment]
Thanks!

**Pull request merged**
