### PR TITLE
add team/repo for openni2_camera

### PR DESCRIPTION
**Pull request by mikeferguson**
This package exists in ROS1 - we're finally getting it ported/released into ROS2

https://github.com/ros-drivers/openni2_camera/tree/ros2

### CODE REVIEW

**Comment by mikeferguson** [comment]
PR to add source entry to rolling is here: https://github.com/ros/rosdistro/pull/36320

**Comment by mikeferguson** [comment]
PR to rosdistro has been accepted and merged

**Comment by mikeferguson** [comment]
@nuclearsandwich - not sure if you get notifications for opening a PR - I think this is ready for your review (it seems you have merged the last few PRs to this repo)

**Comment by nuclearsandwich** [comment]
> not sure if you get notifications for opening a PR - I think this is ready for your review (it seems you have merged the last few PRs to this repo)

I do get notifications here and try to sweep this repo at least once and ideally twice per week.

**Review by nuclearsandwich — APPROVED** [review]

**Comment by nuclearsandwich** [comment]
This change has been deployed!

**Pull request merged**
