### PR TITLE
add perception open3d

### PR DESCRIPTION
**Pull request by wep21**
I would like to release `perception_open3d` packages.
https://github.com/ros-perception/perception_open3d
@SteveMacenski @jacobperron Is it possible for me to join perception.tf?

### CODE REVIEW

**Comment by SteveMacenski** [comment]
That does not relate to this repository, the release repository for perception open3D is https://github.com/ros-gbp/perception_open3d-release

You are not a maintainer on perception_open3d so it would not be appropriate to give you permission to release on it, but you can request one in the issue tracker

**Comment by jacobperron** [comment]
TBH, I'm not familiar with the process related to adding repos / maintainers to these terraform configurations. I think what Steve suggests sounds more appropriate: if you'd like a new release and/or maintainer status, opening a issue [upstream](https://github.com/ros-perception/perception_open3d) makes sense to me.

**Comment by wep21** [comment]
> That does not relate to this repository, the release repository for perception open3D is https://github.com/ros-gbp/perception_open3d-release

I guess it is recommended to use `ros2-gbp` to release ros2 packages.

> You are not a maintainer on perception_open3d so it would not be appropriate to give you permission to release on it, but you can request one in the issue tracker

> I think what Steve suggests sounds more appropriate: if you'd like a new release and/or maintainer status, opening a issue [upstream](https://github.com/ros-perception/perception_open3d) makes sense to me.

I created a [issue](https://github.com/ros-perception/perception_open3d/issues/24) in the upstream repositroy. Thanks.

**Comment by nuclearsandwich** [comment]
> if you'd like a new release and/or maintainer status, opening a issue [upstream](https://github.com/ros-perception/perception_open3d) makes sense to me.

As a point of procedure, I'll second / third this suggestion. It's much easier for me / the ROS infrastructure team to keep on top of requests here if they come directly from existing package maintainers or represent the outcomes of settled discussions elsewhere. I think that an excellent workflow for similar future scenarios is to open an issue upstream either requesting a release or volunteering to help with maintenance workload of making one yourself and once the conversation there settles on an outcome, linking to it in an issue or PR on this repository implementing the desired state.

@wep21 is it alright to close this PR for now? It can be re-opened if needed once https://github.com/ros-perception/perception_open3d/issues/24 is settled.


> > the release repository for perception open3D is https://github.com/ros-gbp/perception_open3d-release

> I guess it is recommended to use ros2-gbp to release ros2 packages.

It is definitely recommended, especially for Galactic and later stable releases, and is all but required for Rolling. I can assist with migrating the current repository contents to the ros2-gbp if a Rolling release is desired.

**Pull request closed without merging**
