### PR TITLE
Add release team and repository for Eclipse ecal.

### PR DESCRIPTION
**Pull request by wep21**
- [source entry](https://github.com/ros/rosdistro/pull/38179)

### CODE REVIEW

**Comment by wep21** [comment]
@FlorianReimold Have you ever done `bloom-release`? If you have no time to handle this, I can do `bloom-release` instead of you.

**Comment by FlorianReimold** [comment]
Until a few minutes ago, I didn't even know what that is!
We are glad for every help we can get, so if you offer to make bloom releases we are glad to accept that offer 😊

**Comment by wep21** [comment]
@nuclearsandwich Could you review this PR?

**Comment by nuclearsandwich** [comment]
This change has been deployed.

**Pull request merged**
