### PR TITLE
Update teams in autoware and tier4

### PR DESCRIPTION
**Pull request by wep21**
- Update teams due to leave from the company and foundation.

### CODE REVIEW

**Comment by wep21** [comment]
@nuclearsandwich Could you reivew this PR?

**Comment by wep21** [comment]
cc @JWhitleyWork @kenji-miyake

**Comment by JWhitleyWork** [comment]
Fine by me.

**Comment by wep21** [comment]
@nuclearsandwich friendly ping

**Review by nuclearsandwich — APPROVED** [review]

**Comment by nuclearsandwich** [comment]
This change has been deployed!

**Pull request merged**
