### PR TITLE
feat: add simple robotics tf

### PR DESCRIPTION
**Pull request by wep21**
- add simple robotics to release [proxsuite](https://github.com/Simple-Robotics/proxsuite)
- Related to https://github.com/Simple-Robotics/proxsuite/pull/181

### CODE REVIEW

**Comment by wep21** [comment]
@jcarpent @wxmerkt @nuclearsandwich Could you review this PR?

**Review by jcarpent — APPROVED** [review]
Fine with me. Thanks a lot @wep21

**Review by wxmerkt — APPROVED** [review]
Thank you @wep21 for the quick action and initiative

**Comment by nuclearsandwich** [comment]
@wep21 can you open a PR on ros/rosdistro which adds source entries for proxsuite to humble or rolling? We're updating the review process so that packages and repositories go through naming review before the release repository is created.

Once it's opened you can link it here and we'll proceed with this PR once it is merged.

**Comment by wep21** [comment]
@nuclearsandwich @jcarpent @wxmerkt 
Here is [the PR](https://github.com/ros/rosdistro/pull/36325). Please check it out.

**Review by nuclearsandwich — APPROVED** [review]

**Comment by nuclearsandwich** [comment]
This change has been deployed!

**Pull request merged**
