### PR TITLE
Update septentrio_users.tf

### PR DESCRIPTION
**Pull request by septentrio-users**

### CODE REVIEW

**Comment by nuclearsandwich** [comment]
In order to make this change, can you please link to a package.xml maintainers entry for the added GitHub user in the source packages?

**Comment by septentrio-users** [comment]
@nuclearsandwich Many thanks! Do you mean I should add an entry such as 

\<maintainer email="tibor.doeme@alumni.ethz.ch"\>Tibor Dome\</maintainer\>

to the package.xml file of the dev2 (which I would use for the ROS2 release) branch of https://github.com/septentrio-gnss/septentrio_gnss_driver/?

Locally I had issues with making bloom aware of the septentrio-users account even after changing git config locally and reinstalling bloom, which is why I thought I might try adding myself here. Specifically I was getting "ERROR: Permission to ros2-gbp/septentrio_gnss_driver_ros2-release.git denied to tibordome"

**Comment by nuclearsandwich** [comment]
> Locally I had issues with making bloom

None of the ROS infrastructure tools are built with support for different credentials in mind. Bloom will use your local git configuration when creating commits on release repositories but committer and author details in git are completely distinct from GitHub access credentials for pushing to repositories. If `septentrio-users` is the account you want to use to push to GitHub then that's the account you should configure for bloom authentication: https://wiki.ros.org/bloom/Tutorials/GithubManualAuthorization

**Comment by nuclearsandwich** [comment]
@septentrio-users any update here? It seems like both user accounts are yours?

**Comment by septentrio-users** [comment]
@nuclearsandwich thank you for the details, we still have to take a look at our bloom authentication methods, if you could bear with us

**Comment by septentrio-users** [comment]
@nuclearsandwich  When I set https://github.com/ros2-gbp/septentrio_gnss_driver_ros2-release as the release repository for bloom-release and my ~/.gitconfig is set up for ``septentrio-users``, I still get ``ERROR: Permission to ros2-gbp/septentrio_gnss_driver_ros2-release.git denied to tibordome`` so it struggles to recognise that I changed all settings from ``tibordome`` to ``septentrio-users``. I have set up the token for ``septentrio-users`` as suggested [here](https://wiki.ros.org/bloom/Tutorials/GithubManualAuthorization).

Ok I've fixed the ``tibordome`` vs ``septentrio-users`` confusion. However, now I get ``ERROR: Permission to ros2-gbp/septentrio_gnss_driver_ros2-release.git denied to septentrio-users``.

**Comment by nuclearsandwich** [comment]
> Ok I've fixed the `tibordome` vs `septentrio-users` confusion. However, now I get `ERROR: Permission to ros2-gbp/septentrio_gnss_driver_ros2-release.git denied to septentrio-users`.

The ros2-gbp invitation for septentrio-users has never been accepted. Invitations expire automatically 7 days after they are sent. Once an invitation has expired, the next time this project is updated and deployed, that invitation is re-sent. According to the logs I have, the invitation has been sent and expired seven times.

It will go out again with today's deployment and you will need to accept it before you can push to the release repository when authenticated as `septentrio-users`.

**Comment by septentrio-users** [comment]
Thank you for sending out the invitation once again @nuclearsandwich . We have accepted it and managed to push to the release repository.

**Comment by nuclearsandwich** [comment]
@septentrio-users does that mean that this PR is no longer required? If that's the case we can close it.

**Pull request closed without merging**
