### PR TITLE
Update autoware team membership.

### PR DESCRIPTION
**Pull request by nuclearsandwich**
* wep21
* kenji-miyake
* mitsudome-r

Based on the initial request in https://github.com/ros2-gbp/ros2_socketcan-release/issues/1

### CODE REVIEW

**Comment by nuclearsandwich** [comment]
@wep21 can you please help fulfill this request by including links which demonstrate that these individuals are maintainers on the autoware projects? Maintainer names in package.xml are the easiest to review but not the only option.

**Comment by wep21** [comment]
@nuclearsandwich
Please see https://github.com/orgs/autowarefoundation/teams/tier4-developers/members.
We are the members from tier4 in autowarefoundation.
I will do some release tasks in autowarefoundation. https://github.com/autowarefoundation/ros2_socketcan/pull/13
@kenji-miyake and @mitsudome-r have maintainer roles in autowarefoundation.
Is it sufficient to prove it?

**Comment by nuclearsandwich** [comment]
Please see [github.com/orgs/autowarefoundation/teams/tier4-developers/members](https://github.com/orgs/autowarefoundation/teams/tier4-developers/members). This page is private otherwise it would be sufficient for verification. @JWhitleyWork since you merged https://github.com/autowarefoundation/ros2_socketcan/pull/13 could you give a :+1: to these new members?

**Comment by JWhitleyWork** [comment]
@nuclearsandwich They're all fine for me.

**Comment by nuclearsandwich** [comment]
This will deploy later today.

**Pull request merged**
