### PR TITLE
Add fields2cover release team and repository.

### PR DESCRIPTION
**Pull request by nuclearsandwich**
I'm importing this release repository ahead of the upcoming Rolling transition to 24.04.
All artifacts from the previous release repository have been imported into this one and the maintainer of the package has been included in the release team.

### CODE REVIEW

**Review by clalancette — APPROVED** [review]

**Comment by nuclearsandwich** [comment]
FYI @Gonzalo-Mier, you'll need to accept the invitation to join the ros2-gbp organization in order to continue making releases to this package for ROS 2 distributions. If you would like to use this repository for noetic releases as well, you could archive the previous release repository to avoid releasing with it by mistake.

**Comment by nuclearsandwich** [comment]
Release repository imported before terraform deployment with

```
bin/import-repo fields2cover-release
```

**Comment by nuclearsandwich** [comment]
This change has been deployed!

**Comment by Gonzalo-Mier** [comment]
Hello @nuclearsandwich,

I miss the invitation mail and it expired. Could you send me the link to join ros2-gbp again, please.

Thank you for your help

**Pull request merged**
