### PR TITLE
Add rplidar release team.

### LINKED ISSUE #236: Add release team
* Name of the new release team: rplidar
* Release repositories to add:
  * [sllidar](https://github.com/Slamtec/sllidar_ros2)
    * https://github.com/Slamtec/sllidar_ros2

* Team members
  * [@slamtec](https://github.com/Slamtec/sllidar_ros2/blob/main/package.xml#L9)

### PR DESCRIPTION
**Pull request by deyouslamtec**
Resolves #236

### CODE REVIEW

**Comment by nuclearsandwich** [comment]
Thanks for opening this PR. What is the overlap of this project with https://github.com/ros2-gbp/rplidar_ros-release?

Before this PR can be merged, can you please open a PR adding a source entry for the new `sllidar_ros2` package in https://github.com/ros/rosdistro which will trigger the new package review there?

**Comment by nuclearsandwich** [comment]
Hello @deyouslamtec any update on the above request?

**Comment by deyouslamtec** [comment]
> Hello @deyouslamtec any update on the above request?

This project may overlaps with this project（https://github.com/ros2-gbp/rplidar_ros-release）, and we are discussing how to solve this problem。

**Comment by nuclearsandwich** [comment]
Thanks for the update. I'm going to close this PR for now. Please feel free to re-open it, or open a new PR when you have a path forward.

**Pull request closed without merging**
