### PR TITLE
Add acceleration_wg team.

### PR DESCRIPTION
**Pull request by nuclearsandwich**
Membership and repository information coming from
https://github.com/ros2-gbp/ros2-gbp-github-org/pull/22

### CODE REVIEW

**Comment by methylDragon** [comment]
Oh whoops, I didn't realize we needed to add to the members and repositories file.

I think @vmayoral doesn't have anyone else to add, so we just need the release repos made/transferred, and we should be good to go!
Thanks so much for getting on this 🙇 

PS: @vmayoral , we can continue tracking the release process in https://github.com/ros2-gbp/ros2-gbp-github-org/pull/22 , anywhere else you'd prefer. I think I will be closing that PR though, and this might get merged, so you might want to consider tracking the process elsewhere.

**Comment by vmayoral** [comment]
Thanks for this @nuclearsandwich and @methylDragon, we're good in terms of team indeed.

**Comment by vmayoral** [comment]
> PS: @vmayoral , we can continue tracking the release process in https://github.com/ros2-gbp/ros2-gbp-github-org/pull/22 , anywhere else you'd prefer. I think I will be closing that PR though, and this might get merged, so you might want to consider tracking the process elsewhere.

@methylDragon I'll continue updating things there, but happy to move that elsewhere once it closes. Just want to update one feed at a time, not many, if that's ok.

**Comment by methylDragon** [comment]
Thanks for the merge! I think we're still pending the repository creation. I think we need new ones made in the org since we only have source repositories.

Or, @vmayoral would you prefer making your own and then transferring them to the org?

**Comment by vmayoral** [comment]
AFAIK, we are waiting for the repos to start the release process. That’s
what was explained in the guide facilitated, right?

**Comment by methylDragon** [comment]
The release repos have been made! Thanks!!

**Comment by nuclearsandwich** [comment]
This change has now been deployed. (As @methylDragon noted above :D)

**Comment by vmayoral** [comment]
Thanks guys!

**Pull request merged**
