### PR TITLE
add rosbag2 storage mcap release repository

### PR DESCRIPTION
**Pull request by wep21**
add release repository for https://github.com/ros-tooling/rosbag2_storage_mcap

### CODE REVIEW

**Comment by wep21** [comment]
@emersonknapp Can I create rosbag2_storage_mcap release repository under tooling_wg group?
cc @jhurliman @jtbandes @nuclearsandwich

**Review by jhurliman — APPROVED** [review]

**Review by jtbandes — APPROVED** [review]

**Review by jhurliman — APPROVED** [review]

**Comment by nuclearsandwich** [comment]
> add release repository for https://github.com/ros-tooling/rosbag2_storage_mcap

Is there an existing release repository that needs to be imported? Otherwise this looks good and I'll merge and deploy it post-haste.

**Comment by jtbandes** [comment]
Nope, there is no existing release repo, the package is new.

**Review by nuclearsandwich — APPROVED** [review]

**Comment by nuclearsandwich** [comment]
This change is now deployed!

**Comment by wep21** [comment]
@nuclearsandwich Thank you for creating the repository. `rosbag2_storage_mcap` uses `conan` as build tool.
Is it acceptable to add rhel key into https://github.com/ros/rosdistro/blob/cc7f421c0bd63bb547baff2a51a9b44a3b3f68d6/rosdep/python.yaml#L6143-L6152?

**Pull request merged**
