### PR TITLE
Updates to wep21 release team repositories.

### PR DESCRIPTION
**Pull request by wep21**
* Archive linear_sum_assignment release repository.
* Add [turbojpeg_compressed_image_transport](https://github.com/wep21/turbojpeg_compressed_image_transport) release repository.

### CODE REVIEW

**Comment by wep21** [comment]
@nuclearsandwich Could you review this PR?

**Comment by nuclearsandwich** [comment]
@wep21 thanks for the ping.

The removed release repository is not a part of any other release teams. While we support empty release teams as a temporary measure we don't allow repositories with no release team. Is linear_sum_assignment a deprecated package, in which case we would remove it from ROS 2 rolling and archive the release repository?

**Comment by wep21** [comment]
@nuclearsandwich Yes, linear_sum_assignment is deprecated, so I appreciate it if you could remove the the release repository.

**Comment by wep21** [comment]
@nuclearsandwich friendly ping

**Comment by nuclearsandwich** [comment]
> Yes, linear_sum_assignment is deprecated, so I appreciate it if you could remove the the release repository.

We don't remove release repositories that are deprecated. Even old release repositories should remain online indefinitely in case someone is working from an old rosdistro that uses them. We can however move the repository into the list of archived repositories, which do not need to have an active release team. I have pushed 766beea which does just that.

**Review by nuclearsandwich — APPROVED** [review]

**Comment by nuclearsandwich** [comment]
This change has been deployed!

**Pull request merged**
