### PR TITLE
Add acceleration release team

### PR DESCRIPTION
**Pull request by methylDragon**
## Description
Release team to prep for release of some [Hardware Acceleration Working Group](https://github.com/ros-acceleration) packages.
I will be adding myself temporarily (@methyldragon) to help with the process.

Currently the packages have upstream repositories only, so I would like to also request that **new release repositories are made on this org**.

After the release team is made, I will be separately making release requests.

## Details
Name of the new release team: acceleration_wg

### Release repositories to create (upstream repositories hyperlinked)
5 repositories in total.

**ament Extensions**
- ament_acceleration-release ([upstream](https://github.com/ros-acceleration/ament_acceleration))
- ament_vitis-release ([upstream](https://github.com/ros-acceleration/ament_vitis))

**Packages**
- vitis_common-release ([upstream](https://github.com/ros-acceleration/vitis_common))
- tracetools_acceleration-release ([upstream](https://github.com/ros-acceleration/tracetools_acceleration))

**ros2cli Extensions**
- ros2acceleration-release ([upstream](https://github.com/ros-acceleration/ros2acceleration))

### Team members
- @vmayoral
- @methyldragon

## Additional Notes
If I need to be adding the release repositories that are yet-to-be-created to the `.tf` group, let me know, and I'll do that!

### CODE REVIEW

**Comment by methylDragon** [comment]
@vmayoral , is there anyone else you'd like to add?

**Comment by methylDragon** [comment]
Also just mentioning the release process issues for backlinking:
https://github.com/ros-acceleration/ament_acceleration/issues/1
https://github.com/ros-acceleration/ament_vitis/issues/1
https://github.com/ros-acceleration/vitis_common/issues/1
https://github.com/ros-acceleration/tracetools_acceleration/issues/1
https://github.com/ros-acceleration/ros2acceleration/issues/2

**Comment by vmayoral** [comment]
Thanks for taking the lead with this @methylDragon! I went through (I hope all of) your tickets to wrap my mind around the feedback for the hardware acceleration packages release. I picked some low hanging fruits (PRs) you sent in the process (thanks for those). In general terms, I'm quite happy with the feedback.

My goal with this comment is to assess the actual effort required to move forward with the complete release and convey it back to Xilinx/AMD for them to decide and assign resources to go ahead and implement the feedback provided.

My notes on the review you've performed below (with some `internal labels` for tracking).

#### Hardware acceleration packages release status
- [ ] `package 1`: [colcon-acceleration](https://github.com/ros-acceleration/colcon-acceleration)
  - [x] evaluation 
    - https://github.com/ros-acceleration/colcon-acceleration/issues/10
    - https://github.com/colcon/colcon-core/issues/493#issuecomment-1071350845
  - [x] code fixes (assigned to: @vmayoral)
    - [x] `colcon` team to review package name and general approach https://github.com/colcon/colcon-core/issues/493#issuecomment-1071350845
    - [x] Resolve their concerns
    - [ ] (*optional*) recommendations https://github.com/ros-acceleration/colcon-acceleration/issues/10#issue-1168063785 @methylDragon
  - [ ] release
    - [ ] Create [`publish-python.yaml`](https://github.com/dirk-thomas/publish-python) file to define the release process
        - See example in [`colcon-core`](https://github.com/colcon/colcon-core/blob/master/publish-python.yaml)
    - [x] Raise issue in [`colcon/colcon-core`](https://github.com/colcon/colcon-core) to request for this repo to be transferred into the `colcon` org (https://github.com/colcon/colcon-core/issues/493)
      - [ ] Migrate package
    - [ ] PR for implementation in the repo in that org to be sent and approved if necessary
- [ ] `package 2`: [ament_acceleration](https://github.com/ros-acceleration/ament_acceleration)
  - [x] evaluation https://github.com/ros-acceleration/ament_acceleration/issues/1
  - [x] code fixes (assigned to: @vmayoral)
    - [x] Create a **release tag** corresponding to the version specified in `package.xml` @vmayoral 
    - https://github.com/ros-acceleration/ament_acceleration/commit/f1568b1a0edc8055c04ca230c523d7f01b653cdc
  - [ ] release
    - [ ] Create release repo (pending https://github.com/ros2-gbp/ros2-gbp-github-org/pull/22)
    - [ ] Do [`bloom` release](https://wiki.ros.org/bloom/Tutorials/FirstTimeRelease)
      - [ ] `bloom` should PR `rosdistro`, if not, **manually create a PR**
    - [ ] `rosdistro` team to review package and merge PR (1-2 days, 1 month to get apt installable)
    - [ ] Monitor build and release status on [repo page](http://repo.ros2.org/status_page/) and [buildfarm](https://build.ros2.org/)
- [ ] `package 3`: [ament_vitis](https://github.com/ros-acceleration/ament_vitis)
  - [x] evaluation https://github.com/ros-acceleration/ament_vitis/issues/1
  - [x] code fixes (assigned to: @vmayoral)
    - [x] Create a **release tag** corresponding to the version specified in `package.xml` @vmayoral 
    - https://github.com/ros-acceleration/ament_vitis/commit/d9ba9c3f342d982fc9d8da816868c15bbdadfa66
    - https://github.com/ros-acceleration/ament_vitis/commit/48683473415eb8a3a2f6e1bd6c4eace635357100
    - https://github.com/ros-acceleration/ament_vitis/commit/bb72b0a8d9b403ebdbc2755708b414674a333c11
  - [ ] release
    - [ ] Create release repo (pending https://github.com/ros2-gbp/ros2-gbp-github-org/pull/22)
    - [ ] Do [`bloom` release](https://wiki.ros.org/bloom/Tutorials/FirstTimeRelease)
      - [ ] `bloom` should PR `rosdistro`, if not, **manually create a PR**
    - [ ] `rosdistro` team to review package and merge PR (1-2 days, 1 month to get apt installable)
    - [ ] Monitor build and release status on [repo page](http://repo.ros2.org/status_page/) and [buildfarm](https://build.ros2.org/)
- [ ] `package 4`: [vitis_common](https://github.com/ros-acceleration/vitis_common)
  - [x] evaluation https://github.com/ros-acceleration/vitis_common/issues/1
  - [x] code fixes (assigned to: @vmayoral)
    - [x] Create a **release tag** corresponding to the version specified in `package.xml` @vmayoral 
  - [ ] release
    - [ ] Create release repo (pending https://github.com/ros2-gbp/ros2-gbp-github-org/pull/22)
    - [ ] Do [`bloom` release](https://wiki.ros.org/bloom/Tutorials/FirstTimeRelease)
      - [ ] `bloom` should PR `rosdistro`, if not, **manually create a PR**
    - [ ] `rosdistro` team to review package and merge PR (1-2 days, 1 month to get apt installable)
    - [ ] Monitor build and release status on [repo page](http://repo.ros2.org/status_page/) and [buildfarm](https://build.ros2.org/)
- [ ] ~~`package 5`: [acceleration_firmware](https://github.com/ros-acceleration/acceleration_firmware)~~
  - [x] ~~evaluation and discussion https://github.com/ros-acceleration/acceleration_firmware/issues/1~~
  - [ ] ~~code fixes ⚫ (assigned to: TBD), I couldn't come up with any good scenario wherein (other than for organizational matters) keeping this package will add significant value from a source code perspective so I'm <ins>biased to recommend to drop it completely</ins>, and modify other packages accordingly. The effort of doing so (modify other packages) is something manageable if considering future firmware releases. See https://github.com/ros-acceleration/acceleration_firmware/issues/1#issuecomment-1070687656~~.
  - [ ] ~~release~~
- [ ] `package 6`: [tracetools_acceleration](https://github.com/ros-acceleration/tracetools_acceleration)
  - [x] evaluation https://github.com/ros-acceleration/tracetools_acceleration/issues/1
  - [x] code fixes (assigned to: @vmayoral)
    - [x] Create a **release tag** corresponding to the version specified in `package.xml` @vmayoral 
  - [ ] release
    - [ ] Create release repo (pending https://github.com/ros2-gbp/ros2-gbp-github-org/pull/22)
    - [ ] Do [`bloom` release](https://wiki.ros.org/bloom/Tutorials/FirstTimeRelease)
      - [ ] `bloom` should PR `rosdistro`, if not, **manually create a PR**
    - [ ] `rosdistro` team to review package and merge PR (1-2 days, 1 month to get apt installable)
    - [ ] Monitor build and release status on [repo page](http://repo.ros2.org/status_page/) and [buildfarm](https://build.ros2.org/)
- [ ] `package 7`: [ros2acceleration](https://github.com/ros-acceleration/ros2acceleration)
  - [x] evaluation https://github.com/ros-acceleration/ros2acceleration/issues/2
  - [x] code fixes (assigned to: @vmayoral)
    - [x] Create a **release tag** corresponding to the version specified in `package.xml` @vmayoral 
  - [ ] release
    - [ ] Create release repo (pending https://github.com/ros2-gbp/ros2-gbp-github-org/pull/22)
    - [ ] Do [`bloom` release](https://wiki.ros.org/bloom/Tutorials/FirstTimeRelease)
      - [ ] `bloom` should PR `rosdistro`, if not, **manually create a PR**
    - [ ] `rosdistro` team to review package and merge PR (1-2 days, 1 month to get apt installable)
    - [ ] Monitor build and release status on [repo page](http://repo.ros2.org/status_page/) and [buildfarm](https://build.ros2.org/)
#### Additional feedback
- https://github.com/colcon/colcon-core/issues/493#issuecomment-1071350845 (🟠)
- https://github.com/ros-acceleration/KRS_private/issues/1 (🟠)
- [Releasing_ROS_2_Packages.pdf](https://github.com/ros2-gbp/ros2-gbp-github-org/files/8315206/Releasing_ROS_2_Packages.pdf)

####  ROS packages release process
1. Getting the package sources in working order (including creating a release tag on the source repository)
2. Making a release repository (separate from the source repository)
3. Doing a release, pushing it to the release repository
4. Sending a PR to rosdistro and getting it merged
5. Checking the buildfarm for successful builds, and waiting for the sources to get synced to the official ROS debian repositories

####  Additional tickets to track
- https://github.com/ros2-gbp/ros2-gbp-github-org/pull/24

**Comment by vmayoral** [comment]
@methylDragon waiting for https://github.com/ros2-gbp/ament_acceleration-release so that I can continue with the release process. Can you please help create this ASAP?

**Comment by vmayoral** [comment]
> - [Releasing_ROS_2_Packages.pdf](https://github.com/ros2-gbp/ros2-gbp-github-org/files/8315206/Releasing_ROS_2_Packages.pdf)

@methylDragon I followed the guidelines you provided but I believe some deserve further clarifications and/or hints. Here're some notes, please comment:
- `python-bloom` has no install candidate in 20.04, I believe what we're aiming for in here is `python3-bloom`
- please provide help and clarity on *Doc Indexing* for these ROS 2 packages, this is unresolved in the document provided. Also, examples and hints of what's ideal/expected for each package would be appreciated. This is also aligned with the `Would you like to add documentation information for this repository?` question raised while *bloom*ing things.
- `Would you like to add source information for this repository?` what's the recommended approach in here while *bloom*ing things?
- At the end of the document, the section on `See how releases get picked up and updated via the buildfarm/CI with this doc` leads to a non-available PDF document. Let us know how to access the latest version of that.

**Comment by methylDragon** [comment]
Hi Victor, yes, use the Python 3 version.

I'll need to check with the rest on the bloom prompts, and I'll email you the attached doc. Apologies for that, it's from my internal notes, so some references might have broken.

I don't have write permissions for the org for the repo creation, but I'll ping someone who does. I'm not sure how long it will take, since everyone's busy with fixing up the buildfarm..

**Comment by methylDragon** [comment]
For the bloom prompts, I am 80% sure you should answer `y` to the prompts and enter the repository URL (the one that ends in `.git`). If you're double unsure, see the [rosdistro yaml](https://github.com/ros/rosdistro/blob/master/foxy/distribution.yaml) , since those links eventually get populated there.

See:
- https://answers.ros.org/question/383108/releasing-packages-with-bloom-what-can-go-in-the-doc-field/

For docs it might be good to look at some reference ros2 packages. Getting the link put into the rosdistro yaml will let the docs get picked up by the indexer, if I'm not mistaken. But what form those docs take, you'll need to look at reference ros2 packages to be sure.

I think either doxygen files or rsts should suffice, but defer to what existing packages do.

For example,

https://github.com/ros2/geometry2/tree/foxy/tf2 has a doxy file that builds the .dox page (and docstrings in the source files), and is reflected in its built form here: https://docs.ros2.org/foxy/api/tf2/

In this case, the doc member in the rosdistro yaml (remember that indexing is just having the member be populated on rosdistro) allows the buildfarm to pick up the repo, and automatically build and publish the docs.

**Comment by vmayoral** [comment]
Ok, thanks for the clarifications @methylDragon. This together with the `ROS 2 Buildfarm Overview` document partially addresses some of the concerns above. No follow up questions for now.

My goal will be to focus on getting the code fixes that derive from the reviews above and I will let you guys take care of the subtleties of the build farm/s yourselves, if any in the next steps. Please ping me once we've got the releases repos available in this org if you need me to submit the bloom releases myself. Happy to pick that step as well.

**Comment by vmayoral** [comment]
All right, I believe to have addressed major code fixes and concerns in packages: `package 1`, `package 2` and `package 3` above. Looking now at the rest.

**Comment by vmayoral** [comment]
Removed all dependencies with respect [acceleration_firmware](https://github.com/ros-acceleration/acceleration_firmware), future releases and packages won't depend on this. Crossed it over in the list above.

**Comment by vmayoral** [comment]
@methylDragon, I believe to have addressed most major roadblocks and critical concerns in all packages above. Let me know once we can move forward with the release phase.

**Comment by methylDragon** [comment]
Reviewing on my end

**Comment by methylDragon** [comment]
Some changes needed, I've labelled the tracking issues accordingly, we're making progress!

**Comment by nuclearsandwich** [comment]
Closing now that #24 has merged.

**Pull request closed without merging**
