### PR TITLE
Update mrpt2.tf

### PR DESCRIPTION
**Pull request by jlblancoc**
Add two new repositories under the mrpt2 organization

### CODE REVIEW

**Comment by nuclearsandwich** [comment]
Thanks for the PR @jlblancoc, I don't foresee any REP-144 related naming issues but could you add source entries for these two new repositories to ros/rosdistro (under any one current ROS 2 distro is sufficient) to ensure that they receive naming and license review before the release repositories are created. Once the PRs are opened you can link them here and I'll try to keep an eye on when they merge in order to proceed.

**Comment by jlblancoc** [comment]
Ok. 
- [X] mrpt_path_planning already done and merged https://github.com/ros/rosdistro/pull/37450
- [x] mp2p_icp : https://github.com/ros/rosdistro/pull/37569

**Comment by jlblancoc** [comment]
Updated comment above. TL;DR ==> https://github.com/ros/rosdistro/pull/37569

**Comment by nuclearsandwich** [comment]
Thanks! I didn't yet connect that mrpt_path_planning was the outcome from https://github.com/ros/rosdistro/pull/37450 once the mp2p_icp also passes we'll be able to move forward.

**Review by nuclearsandwich — APPROVED** [review]
I re-sorted the list of repositories so it is in lexicographical order but otherwise this change is ready to go. Thanks!

**Pull request merged**
