### PR TITLE
Update PickNik team

### PR DESCRIPTION
**Pull request by ChrisThrasher**

### CODE REVIEW

**Review by tylerjw — APPROVED** [review]
Thank you for making this PR. We'd like to add these two people to our release team and add these three release repos to our team which we manage.

**Review by sea-bass — APPROVED** [review]
Thanks for adding me and `pick_ik` to this!

**Comment by nuclearsandwich** [comment]
@ChrisThrasher @tylerjw these repositories are already in the [moveit team](https://github.com/ros2-gbp/ros2-gbp-github-org/blob/latest/moveit.tf) as well.
This isn't a problem and these scripts were designed to allow multiple different teams to have permissions on a release repository specifically to cover access via different "roles".
So this is just a head's up not a blocker.

**Review by nuclearsandwich — APPROVED** [review]
I'm taking @tylerjw's approval together with his existing team membership as PickNik approval for these new team members.

**Comment by nuclearsandwich** [comment]
This change has been deployed!

**Pull request merged**
