### PR TITLE
Updates PickNik team membership

### LINKED ISSUE #280: Update release team membership
# Updates to `picknik_team` membership.

## New team members

[@moriarty](https://github.com/PickNikRobotics/ros2_robotiq_gripper/blob/58eda4b7f58052c427e79cec09bd4b302dcdd3cb/robotiq_description/package.xml#L8)
[@marqrazz](https://github.com/PickNikRobotics/ros2_robotiq_gripper/blob/58eda4b7f58052c427e79cec09bd4b302dcdd3cb/robotiq_description/package.xml#L9)

### PR DESCRIPTION
**Pull request by moriarty**
This fixes #280

### CODE REVIEW

**Comment by moriarty** [comment]
FYI @MarqRazz

**Review by MarqRazz — APPROVED** [review]

**Review by mjcarroll — APPROVED** [review]

**Comment by moriarty** [comment]
@mjcarroll you approved but it's still waiting for a approval from a maintainer, I don't see a .github/CODEOWNERS file or equivalent to know who should be assigned to this issue.

Is it only OSRC or the whatever the new team within Intrinsic who are able to approve and merge these PRs?

Maybe adding something like this: https://probot.github.io/apps/auto-assign/ would be a good way of randomly assigning reviewers from a pool of eligible reviewers?

**Comment by mjcarroll** [comment]
This one is up to @nuclearsandwich, I believe.  I don't have write privileges in here, but I approved it as part of my rotation on rosdistro this week.

**Review by nuclearsandwich — APPROVED** [review]

**Comment by nuclearsandwich** [comment]
> Is it only OSRC or the whatever the new team within Intrinsic who are able to approve and merge these PRs?

This organization is maintained by OSRF, specifically the Infrastructure Project Committee for which I'm the appointed maintainer of this project although not the only one with capability to deploy in the event I'm inaccessible. I usually try to sweep through at least twice a week and we're working some tooling that will make deployment, and thus maintainership, for this project easier to share across the team.

**Pull request merged**
