### PR TITLE
Add new release repository for mvsim

### PR DESCRIPTION
**Pull request by jlblancoc**

### CODE REVIEW

**Comment by jlblancoc** [comment]
A release repo for the package mvsim exists [here](https://github.com/ual-arm-ros-pkg-release/mvsim-release) for ROS1, but now we want to make the first release for ROS2. 

Is this change all that is needed to get the release repository created automatically?

Show I create the release repo somewhere else and then *transfer* it to ros2-gbp or you/some bot will create it automatically?

Thanks

**Comment by nuclearsandwich** [comment]
> Is this change all that is needed to get the release repository created automatically?

Yes, once this change is merged and deployed, the repository will be automatically created.

> Show I create the release repo somewhere else and then _transfer_ it to ros2-gbp or you/some bot will create it automatically?

If there is an existing release repository for ROS 2. The current practice that we recommend is to archive the existing repository so it is retained forever as read-only (whereas GitHub redirects after transfers are not guaranteed indefinitely) and I can mirror the contents to the ros2-gbp organization's repository so that it can be used for all ROS 2 distributions and future releases going forward.

**Review by nuclearsandwich — APPROVED** [review]

**Comment by jlblancoc** [comment]
Great, thanks for the quick answer and merge! 
Nope, there is currently no ROS2 release repository yet, so no need to import anything.

**Comment by nuclearsandwich** [comment]
This change has been deployed so the repository has been created.

**Comment by jlblancoc** [comment]
Awesome, thanks!

**Pull request merged**
